import type {Metadata} from "next";
import {Rosario} from "next/font/google";
import "./globals.css";
import React from "react";
import Navbar from "@/components/layout/Navbar";

const rosario = Rosario({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" className="dark">
            <body className={rosario.className}>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
